name: Parrallel Jobs

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the Environment'
        required: true
        default: 'Development'
        type: choice
        options:
            - Development
            - Staging
            - Production
  
jobs:
  git-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: echo "Checked out the repository."
  
  build:
    runs-on: ubuntu-latest
    needs: git-checkout
    steps:
      - name: Build project
        run: echo "Building the project..."
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: echo "Running tests..."